modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="minepiece_goated_edition"
version="1.0.0"
displayName="minepiece goated edition"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="beanpack, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minepiece_goated_edition]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.minepiece_goated_edition]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration
